services:
  - type: web
    name: whatsapp-flask-app
    region: oregon
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    runtime: python
    envVars:
      - key: FLASK_ENV
        value: production
